Brickstorm\WorldBundle\Entity\City:
  type: entity
  table: b_world__city
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 250
      fixed: false
      nullable: false
    population:
      type: integer
      nullable: true
    latitude:
      type: float
      nullable: true
    longitude:
      type: float
      nullable: true
    created_at:
      type: date
      gedmo:
        timestampable:
          on: create
    updated_at:
      type: datetime
      gedmo:
        timestampable:
          on: update
  manyToOne:
    province:
      targetEntity: Province
      joinColumns:
        province_id:
          referencedColumnName: id
          nullable: true
    country:
      targetEntity: Country
      joinColumns:
        country_id:
          referencedColumnName: id
          nullable: true
    parent:
      targetEntity: City
      inversedBy: children  
      joinColumns:
        parent_id:
          nullable: true
          referencedColumnName: id
  lifecycleCallbacks: {  }
