Brickstorm\WorldBundle\Entity\Location:
  type: entity
  table: b_world__location
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 250
    adress:
      type: string
      length: 250
    zipcode:
      type: integer
    url:
      type: string
      length: 250
    email:
      type: string
    twitterhash:
      type: string
    created_at:
      type: date
      gedmo:
        timestampable:
          on: create
    updated_at:
      type: datetime
      gedmo:
        timestampable:
          on: update
  oneToMany:
    children:
      nullable: true
      targetEntity: Location
      mappedBy: parent
  manyToOne:
    parent:
      nullable: true
      targetEntity: Location
      inversedBy: children  
  manyToOne:
    city:
      targetEntity: City
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        city_id:
          referencedColumnName: id
      orphanRemoval: false
    type:
      targetEntity: LocationType
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        type_id:
          referencedColumnName: id
      orphanRemoval: false
    user:
      targetEntity: \Application\Sonata\UserBundle\Entity\User
      inversedBy: locations  
      joinColumns:
        user_id:
          nullable: true
          referencedColumnName: id
  lifecycleCallbacks: {  }
