# Stof
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree:           false
            timestampable:  true
            sluggable:      true
            translatable:   true
            loggable:       true

services:

##Brickstorm

#FacebookGraphBundle

    #world
    brsm.world.admin.city:
        class: Brickstorm\WorldBundle\Admin\CityAdmin
        tags: 
            - { name: sonata.admin, manager_type: orm, group: World, label: City }
        arguments: [null, Brickstorm\WorldBundle\Entity\City, BrickstormWorldBundle:Admin\CityAdmin] 
    brsm.world.admin.province:
        class: Brickstorm\WorldBundle\Admin\ProvinceAdmin
        tags: 
            - { name: sonata.admin, manager_type: orm, group: World, label: Province }
        arguments: [null, Brickstorm\WorldBundle\Entity\Province, BrickstormWorldBundle:Admin\ProvinceAdmin] 
    brsm.world.admin.country:
        class: Brickstorm\WorldBundle\Admin\CountryAdmin
        tags: 
            - { name: sonata.admin, manager_type: orm, group: World, label: Country }
        arguments: [null, Brickstorm\WorldBundle\Entity\Country, BrickstormWorldBundle:Admin\CountryAdmin] 
    brsm.world.admin.continent:
        class: Brickstorm\WorldBundle\Admin\ContinentAdmin
        tags: 
            - { name: sonata.admin, manager_type: orm, group: World, label: Continent }
        arguments: [null, Brickstorm\WorldBundle\Entity\Continent, BrickstormWorldBundle:Admin\ContinentAdmin]  