# Stof
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree:           false
            timestampable:  true
            sluggable:      true
            translatable:   true
            loggable:       true

services:

##Brickstorm

#FacebookGraphBundle

    #world
    brsm.world.admin.city:
        class: Brickstorm\SolidRBundle\Admin\CityAdmin
        tags: 
            - { name: sonata.admin, manager_type: orm, group: World, label: City }
        arguments: [null, Brickstorm\SolidRBundle\Entity\City, BrickstormSolidRBundle:Admin\CityAdmin] 
    brsm.world.admin.province:
        class: Brickstorm\SolidRBundle\Admin\ProvinceAdmin
        tags: 
            - { name: sonata.admin, manager_type: orm, group: World, label: Province }
        arguments: [null, Brickstorm\SolidRBundle\Entity\Province, BrickstormSolidRBundle:Admin\ProvinceAdmin] 
    brsm.world.admin.country:
        class: Brickstorm\SolidRBundle\Admin\CountryAdmin
        tags: 
            - { name: sonata.admin, manager_type: orm, group: World, label: Country }
        arguments: [null, Brickstorm\SolidRBundle\Entity\Country, BrickstormSolidRBundle:Admin\CountryAdmin] 
    brsm.world.admin.continent:
        class: Brickstorm\SolidRBundle\Admin\ContinentAdmin
        tags: 
            - { name: sonata.admin, manager_type: orm, group: World, label: Continent }
        arguments: [null, Brickstorm\SolidRBundle\Entity\Continent, BrickstormSolidRBundle:Admin\ContinentAdmin]  